name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - name: Domain typecheck
        run: npm run typecheck --workspace=packages/domain
      - name: Domain unit tests
        run: npm run test --workspace=packages/domain
      - name: Data typecheck
        run: npm run typecheck --workspace=packages/data
      - name: Data unit tests
        run: npm run test --workspace=packages/data
      - name: Presentation typecheck
        run: npm run typecheck --workspace=packages/presentation
      - name: Presentation unit tests
        run: npm run test --workspace=packages/presentation
      - name: Mainfeed typecheck
        run: npm run typecheck --workspace=apps/mainfeed
      - name: Mainfeed build
        run: npm run build --workspace=apps/mainfeed
